services:
  - type: web
    name: promohub-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: promohub_super_secret_jwt_key_2026
      - key: CLIENT_ORIGIN
        value: "*"
