// Master Flash Sale Event Target Date (Always synchronized to 14 Days to D-Day)
export const EVENT_START_DATE = new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_DEALS = [
  {
    id: 1,
    brand: "Sony",
    title: "Sony WH-1000XM5 Wireless Headphones",
    description: "Industry-leading noise canceling headphones with dual processors, 8 microphones, and 30-hour battery.",
    price: 149.99,
    original_price: 399.99,
    total_stock: 50,
    stock_remaining: 50,
    start_time: new Date(Date.now() - 3600000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Audio",
    interested_count: 1080,
    is_interested: false
  },
  {
    id: 2,
    brand: "Apple",
    title: "Apple Watch Series 9 GPS 45mm",
    description: "Always-on Retina display, S9 SiP chip, double tap gesture, and comprehensive health monitoring.",
    price: 199.00,
    original_price: 429.00,
    total_stock: 30,
    stock_remaining: 30,
    start_time: new Date(Date.now() - 7200000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Wearables",
    interested_count: 420,
    is_interested: false
  },
  {
    id: 3,
    brand: "Keychron",
    title: "Keychron Q1 Pro Wireless Mechanical Keyboard",
    description: "Custom QMK/VIA full-aluminum hot-swappable keyboard with double-gasket design and RGB backlight.",
    price: 69.50,
    original_price: 199.00,
    total_stock: 100,
    stock_remaining: 100,
    start_time: new Date(Date.now() - 7200000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Peripherals",
    interested_count: 890,
    is_interested: false
  },
  {
    id: 4,
    brand: "Anker",
    title: "Anker 737 Power Bank (PowerCore 24K)",
    description: "24,000mAh 140W 3-port ultra-fast portable charger with smart digital display.",
    price: 49.99,
    original_price: 149.99,
    total_stock: 80,
    stock_remaining: 80,
    start_time: new Date(Date.now() - 3600000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: false,
    category: "Accessories",
    interested_count: 510,
    is_interested: false
  },
  {
    id: 5,
    brand: "Samsung",
    title: "Samsung T7 Shield 2TB Portable SSD",
    description: "Rugged external solid state drive with IP65 water/dust resistance and up to 1,050MB/s read speeds.",
    price: 79.99,
    original_price: 219.99,
    total_stock: 40,
    stock_remaining: 40,
    start_time: new Date(Date.now() - 3600000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Storage",
    interested_count: 360,
    is_interested: false
  },
  {
    id: 6,
    brand: "Bose",
    title: "Bose QuietComfort Ultra Wireless Earbuds",
    description: "Spatial audio with world-class noise cancellation and custom-tuned sound profile.",
    price: 129.00,
    original_price: 299.00,
    total_stock: 45,
    stock_remaining: 45,
    start_time: new Date(Date.now() - 1000000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Audio",
    interested_count: 620,
    is_interested: false
  },
  {
    id: 7,
    brand: "Logitech",
    title: "Logitech MX Master 3S Performance Mouse",
    description: "8K DPI track-on-glass sensor, Quiet Clicks, and electromagnetic MagSpeed scrolling wheel.",
    price: 39.99,
    original_price: 99.99,
    total_stock: 60,
    stock_remaining: 60,
    start_time: new Date(Date.now() - 3600000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: false,
    category: "Peripherals",
    interested_count: 750,
    is_interested: false
  },
  {
    id: 8,
    brand: "Dyson",
    title: "Dyson Supersonic Airwrap Multi-Styler Complete",
    description: "Engineered for multiple hair types with Coanda airflow control and intelligent heat regulation.",
    price: 249.00,
    original_price: 599.00,
    total_stock: 15,
    stock_remaining: 15,
    start_time: new Date(Date.now() - 1800000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Lifestyle",
    interested_count: 240,
    is_interested: false
  },
  {
    id: 9,
    brand: "Nintendo",
    title: "Nintendo Switch OLED Model Special Edition",
    description: "Vibrant 7-inch OLED screen, wide adjustable stand, wired LAN port dock, and 64GB storage.",
    price: 179.99,
    original_price: 349.99,
    total_stock: 35,
    stock_remaining: 35,
    start_time: new Date(Date.now() - 7200000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Gaming",
    interested_count: 420,
    is_interested: false
  },
  {
    id: 10,
    brand: "LG",
    title: "LG UltraGear 27\" QHD Gaming Monitor 165Hz",
    description: "Nano IPS 1ms G-SYNC compatible display with HDR400 and ultra-thin bezel design.",
    price: 159.00,
    original_price: 379.00,
    total_stock: 20,
    stock_remaining: 20,
    start_time: new Date(Date.now() - 1000000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: false,
    category: "Displays",
    interested_count: 180,
    is_interested: false
  },
  {
    id: 11,
    brand: "DJI",
    title: "DJI Mini 3 Lightweight Camera Drone 4K",
    description: "Under 249g ultra-compact drone with 4K HDR video, true vertical shooting, and 38-min flight time.",
    price: 249.00,
    original_price: 559.00,
    total_stock: 25,
    stock_remaining: 25,
    start_time: new Date(Date.now() - 1200000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Cameras",
    interested_count: 640,
    is_interested: false
  },
  {
    id: 12,
    brand: "PlayStation",
    title: "Sony PlayStation 5 Slim Digital Console",
    description: "Next-gen gaming powerhouse with ultra-high speed 1TB SSD, ray tracing, and Tempest 3D Audio.",
    price: 289.99,
    original_price: 449.99,
    total_stock: 18,
    stock_remaining: 18,
    start_time: new Date(Date.now() - 4500000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Gaming",
    interested_count: 1420,
    is_interested: false
  },
  {
    id: 13,
    brand: "Marshall",
    title: "Marshall Stanmore III Bluetooth Speaker",
    description: "Legendary iconic room-filling acoustic soundstage with analog brass knobs and Bluetooth 5.2.",
    price: 169.00,
    original_price: 379.99,
    total_stock: 30,
    stock_remaining: 30,
    start_time: new Date(Date.now() - 2400000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: false,
    category: "Audio",
    interested_count: 480,
    is_interested: false
  },
  {
    id: 14,
    brand: "Kindle",
    title: "Amazon Kindle Paperwhite Signature Edition",
    description: "32GB storage, wireless charging, auto-adjusting front light, and glare-free 6.8\" 300 ppi display.",
    price: 89.99,
    original_price: 189.99,
    total_stock: 50,
    stock_remaining: 50,
    start_time: new Date(Date.now() - 3600000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: false,
    category: "Lifestyle",
    interested_count: 310,
    is_interested: false
  },
  {
    id: 15,
    brand: "GoPro",
    title: "GoPro HERO12 Black 5.3K Action Camera",
    description: "HyperSmooth 6.0 video stabilization, HDR video, dual LCD screens, and waterproof to 33ft.",
    price: 219.00,
    original_price: 399.99,
    total_stock: 35,
    stock_remaining: 35,
    start_time: new Date(Date.now() - 5400000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Cameras",
    interested_count: 530,
    is_interested: false
  },
  {
    id: 16,
    brand: "Razer",
    title: "Razer DeathAdder V3 Pro Wireless Mouse",
    description: "63g ultra-lightweight esports ergonomic mouse with Focus Pro 30K optical sensor and Gen-3 switches.",
    price: 69.00,
    original_price: 149.99,
    total_stock: 45,
    stock_remaining: 45,
    start_time: new Date(Date.now() - 1800000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: false,
    category: "Peripherals",
    interested_count: 390,
    is_interested: false
  },
  {
    id: 17,
    brand: "Google",
    title: "Google Pixel Watch 2 WiFi + LTE",
    description: "Advanced heart rate tracking, stress detection, Fitbit health integration, and all-day battery.",
    price: 149.00,
    original_price: 399.00,
    total_stock: 22,
    stock_remaining: 22,
    start_time: new Date(Date.now() - 6000000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: false,
    category: "Wearables",
    interested_count: 410,
    is_interested: false
  },
  {
    id: 18,
    brand: "Sennheiser",
    title: "Sennheiser Momentum 4 Wireless Headphones",
    description: "Audiophile-inspired 42mm transducer system, adaptive ANC, and unmatched 60-hour battery life.",
    price: 179.99,
    original_price: 379.95,
    total_stock: 28,
    stock_remaining: 28,
    start_time: new Date(Date.now() - 7200000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Audio",
    interested_count: 560,
    is_interested: false
  },
  {
    id: 19,
    brand: "Garmin",
    title: "Garmin Forerunner 265 GPS Running Watch",
    description: "Colorful AMOLED touchscreen display, training readiness metrics, and multi-band GNSS accuracy.",
    price: 249.00,
    original_price: 449.99,
    total_stock: 15,
    stock_remaining: 15,
    start_time: new Date(Date.now() - 3600000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: false,
    category: "Wearables",
    interested_count: 340,
    is_interested: false
  },
  {
    id: 20,
    brand: "Asus",
    title: "ASUS ROG Ally Handheld Gaming Z1 Extreme",
    description: "120Hz FHD display, AMD Ryzen Z1 Extreme processor, 512GB NVMe SSD, and Windows 11 gaming.",
    price: 399.00,
    original_price: 699.99,
    total_stock: 12,
    stock_remaining: 12,
    start_time: new Date(Date.now() - 1000000).toISOString(),
    end_time: EVENT_START_DATE,
    is_featured: true,
    category: "Gaming",
    interested_count: 980,
    is_interested: false
  }
];
